openwisp/netjsongraph.js

- examples/custom-attributes.html
- examples/netjson-custom.json
and adjust colors and ethernet-opacity.
here an example:
http://intercity-vpn.de/networks/giancarlo/meshrdf/netjson.html
> custom attributes example: add 'ethernet' and 'weak wireless'

- .gitignore
- README.rst
- package.json
- webpack.config.prod.js
- yarn.lock
add build scripts using webpack
> Build Scripts

- .gitignore
- README.rst
- package.json
- webpack.config.prod.js
- yarn.lock
@geekplux from now on push directly to the gsoc17 branch so I can avoid doing this
> [Packaging] added build scripts

- webpack.config.js
Refer to https://github.com/webpack/webpack-dev-server/issues/66
> [Packaging] updated webpack configuration

- src/js/netjsongraph.render.js
> [change] Fix zoom animation #120

- README.md
> [docs] Provide upgrade path to new version

- .github/workflows/ci.yml
- index.html
- package.json
- public/example_templates/netjson-clustering.html
- public/example_templates/netjson-dateParse.html
- public/example_templates/netjson-multipleInterfaces.html
- public/example_templates/netjson-searchElements.html
- public/example_templates/netjson-switchGraphMode.html
- public/example_templates/netjson-switchRenderMode.html
- public/example_templates/netjsongraph-elementsLegend.html
- public/example_templates/netjsongraph-graphGL.html
- public/example_templates/netjsongraph-multipleLinks.html
- public/example_templates/netjsongraph-nodeExpand.html
- public/example_templates/netjsongraph.html
- public/example_templates/netjsonmap-animation.html
- public/example_templates/netjsonmap-appendData.html
- public/example_templates/netjsonmap-appendData2.html
- public/example_templates/netjsonmap-indoormap.html
- public/example_templates/netjsonmap-multipleTiles.html
- public/example_templates/netjsonmap-nodeTiles.html
- public/example_templates/netjsonmap-plugins.html
- public/example_templates/netjsonmap.html
- public/example_templates/njg-geojson.html
- src/js/netjsongraph.config.js
- test/netjsongraph.spec.js
- webpack.config.js
> [ci] Deploy to gh-pages automatically #172

- public/example_templates/netjsonmap-indoormap.html
- src/js/netjsongraph.render.js
> [chores] Minor improvements

- .eslintrc.js
- package.json
- src/js/netjsonWorker.js
- src/js/netjsongraph.render.js
- Use `throw` instead of logging in some cases.
- Silence the eslint warnings.
> [chores] Improve code quality

- .github/workflows/ci.yml
> [ci] Enabled CI on master

- CHANGELOG.rst
- README.md
Prepared the changelog for the upcoming release of netjsongraph.js
> [docs] Prepare the change log

- yarn.lock
Bump follow-redirects to 1.14.8.
Manual reopening of #108.
> [deps] Bump follow-redirects to 1.14.8

- package.json
- yarn.lock
Reverts 297dfa630b72ed886dd8f53fa1e0ecd21d92210f
> [deps] Reverted echarts upgrade

- src/js/netjsongraph.util.js
The `fetch` requests will include credentials which is required for CORS requires.
Related to https://github.com/openwisp/docker-openwisp/issues/353
> [change] Include credentials in fetch requests

- CHANGELOG.rst
- package.json
> 0.2.0 release

- index.html
- package.json
Closes #306 .
Enhanced the UI of examples page also added a toggle button at top right corner for dark mode + added smoother animations on hovering the options for a modern UI look.
> Added toggle button for dark mode resolve #306

- .github/workflows/ci.yml
- test/browser.test.utils.js
Add more headless options for testing purposes.
> [ci] Added more chromedriver headless options

- src/css/netjsongraph.css
This PR improves CSS maintainability by addressing redundant styles, ensuring consistency, and enhancing readability.  
- Removed redundant `font-family` declarations on `body` and standardized to `sans-serif`.  
- Updated `.iconfont` declarations to include a `serif` fallback for better compatibility.  
- Replaced `"0px"` with `"0"` for margin properties to maintain consistency.  
- Improved overall formatting and structure for better maintainability.  
Closes #343
> Refactor CSS for consistency and clarity

- src/js/netjsongraph.core.js
- src/js/netjsongraph.render.js
- src/js/netjsongraph.util.js
Updated the Echarts rendering logic to wrok with
Closes #<issue-number>.
Please [open a new issue](https://github.com/openwisp/netjsongraph.js/issues/new/choose) if there isn't an existing issue yet.
Please describe these changes.
Please include any relevant screenshots.
> [fix] Updated the Echarts rendering

- src/js/netjsongraph.render.js
- src/js/netjsongraph.util.js
- test/netjsongraph.render.test.js
Closes #<issue-number>.
Please [open a new issue](https://github.com/openwisp/netjsongraph.js/issues/new/choose) if there isn't an existing issue yet.
Please describe these changes.
Please include any relevant screenshots.
> [fix] Updated Test Cases

- package.json
- src/js/netjsongraph.render.js
- test/netjsongraph.duplicateNodes.test.js
- test/netjsongraph.render.test.js
Closes #<issue-number>.
Please [open a new issue](https://github.com/openwisp/netjsongraph.js/issues/new/choose) if there isn't an existing issue yet.
Please describe these changes.
Please include any relevant screenshots.
> Streamline map rendering

- package.json
- yarn.lock
It seems that #416 didn't update this dependency properly.
> [deps] Fixed prettier version in package.json and yarn.lock
